# Site settings
title: Programming Blog
email: dhdersch@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hello, I am Daniel Dersch and welcome to my programming blog!
baseurl: "" 
url: "https://dhdersch.github.io"
twitter_username: danieldersch
github_username:  dhdersch

# Build settings
markdown: kramdown
