# Site settings
title: Programming Blog
email: dhdersch@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hello, I am Daniel Dersch and welcome to my programming blog!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://dhdersch.github.io" # the base hostname & protocol for your site
twitter_username: danieldersch
github_username:  dhdersch

# Build settings
markdown: kramdown
